---
# Tasks for network
- name: Set /etc/network/interfaces
  template: >
    dest=/etc/network/interfaces
    src=interfaces.j2
    owner=root
    group=root
    mode=0644
  notify: cycle interfaces
  # tags:
  #   - example

- name: Set gateway via dhclient options
  lineinfile: 
    dest: /etc/dhcp/dhclient.conf
    regexp: '^supersede routers'
    line: 'supersede routers {{ development_vm.network.gateway }};'
  notify: cycle interfaces
