---
# Tasks for timezone

- name: Link proper timezone info
  file:
    src: /usr/share/zoneinfo/{{ development_vm.timezone.name }}
    dest: /etc/localtime
    state: link
  notify: dpkg-reconfigure tzdata
  tags:
    - timezone
