---
# Tasks for user

- name: add defined user group
  action: group name={{development_vm.user.username | mandatory}} gid={{development_vm.user.gid | default(omit) }} state=present

- name: add user with defined uid
  action: user
    name="{{development_vm.user.username | mandatory}}"
    uid="{{development_vm.user.uid | default(omit) }}"
    shell=/bin/bash
    group="{{development_vm.user.username | mandatory}}"
    groups="{{ development_vm.user.groups | default("sudo,vboxsf,vagrant") }}"
    append=no
    password="{{ 'password' | password_hash('sha512') }}"
    update_password=on_create
    state=present
  register: user

- name: Force user to change password
  shell: chage -d 0 {{development_vm.user.username | mandatory}}
  when: user.changed

# Install an SSH key for the user if specified
- name: install user SSH key
  action: authorized_key user={{ development_vm.user.username | mandatory }} key="{{development_vm.user.sshkey}}"
  when: development_vm.user.sshkey is defined
